import Head from 'next/head'
import { Rubik } from 'next/font/google'
import { useState, useRef, useEffect } from "react";
import axios from 'axios'
import dynamic from "next/dynamic";
import React from "react";
import Spinners from '../component/spinners'

const rubik = Rubik({ subsets: ['latin'] })
const MapWithNoSSR = dynamic(() => import("../component/map"), {
  ssr: false,
});

export default function Home() {


  const [value, setValue] = useState("");
  const [ip, setIp] = useState("--");
  const [country, setCountry] = useState("--");
  const [region, setRegion] = useState("--");
  const [timezone, setTimezone] = useState("--");
  const [isp, setIsp] = useState("--");
  const API_KEY = "at_Mn48CScZfOWHr3ooGmQ8It6wCkKzB";
  const loadingRef = useRef(null);
  const [geoData, setGeoData] = useState({ lat: 25.04776, lng: 121.53185 });
  // const [search, setSearch] = useState("");
  // const ipAddress = "ipAddress=" + value;
  // const domain = "domain=" + value;



  const handleValue = (e) => {
    setValue(e.target.value);
    // setSearch(e.target.value);
  }

  
  const handleId = (e) => {
    e.preventDefault()
    setValue("")
    loadingRef.current.className = "mask d-block";

    // console.log(typeof(value))
    // console.log(search)
    // console.log(domain);

    // if (typeof(value) === typeof number){
    //   setSearch(ipAddress);
    // } else if (typeof value === typeof string) {
    //   setSearch(domain);
    // } else {
    //   alert("plz enter a valid IP address or domain");
    // }

      axios
        .get(
          // `https://ipinfo.io/${value}?token=fdbf0c9865cf99`
          `https://geo.ipify.org/api/v2/country,city?apiKey=at_Q4hR6G8UXZDHQLlmuZfHlm5q5Ik7W&ipAddress=${value}`
        )
        .then(function (response) {
          // console.log(response);
          if (
            (value === response.data.ip || value === response.domain) &&
            response.status === 200
          ) {
            setIp(response.data.ip);
            setCountry(response.data.location.country);
            setRegion(response.data.location.region);
            setTimezone(response.data.location.timezone);
            setIsp(response.data.isp);
            setGeoData({
              lat: response.data.location.lat,
              lng: response.data.location.lng,
            });
            console.log("ok");
            console.log(response);
            console.log(response.data.domains);
            loadingRef.current.className = "mask d-none";
          } else if (value === "0" || value === "") {
            setIp("--");
            setCountry("--");
            setRegion("--");
            setTimezone("--");
            setIsp("--");
            alert("Error");
            loadingRef.current.className = "mask d-none";
          }
        })
        .catch((err) => {
          setIp("--");
          setCountry("--");
          setRegion("--");
          setTimezone("--");
          setIsp("--");
          console.log("Error");
          loadingRef.current.className = "mask d-none";
        });
  }

  


  return (
    <>
      <Spinners loadingRef={loadingRef} />
      <Head>
        <title>IP Address Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="wrapper"></div>
        <div id="map">
          <MapWithNoSSR geoData={geoData} />
        </div>
        <div className="container">
          <div className="row">
            <div className="col-12 d-flex flex-column gap-md-5 gap-2 align-items-center">
              <div className="col-12 d-flex flex-column mt-5 gap-3 align-items-center">
                <h1 className="text-center text-white">IP Address Tracker</h1>
                <div className="col-12 col-md-8">
                  <form
                    className="input-group mb-3 searchIDGroup"
                    onSubmit={handleId}
                  >
                    <input
                      type="text"
                      className="form-control searchID"
                      placeholder="Search for any IP address or domain"
                      aria-label="Recipient's username"
                      aria-describedby="button-addon2"
                      value={value}
                      onChange={handleValue}
                    />
                    <button className="btn btn-secondary" type="submit">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        fill="currentColor"
                        className="bi bi-chevron-right"
                        viewBox="0 0 16 16"
                      >
                        <path
                          fillRule="evenodd"
                          d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"
                        />
                      </svg>
                    </button>
                  </form>
                </div>
              </div>
              <div className="d-flex flex-column flex-lg-row bg-white info col-12 col-md-11 justify-content-between">
                <div className="d-flex flex-column gap-lg-3 gap-1 infoBlock">
                  <small className="text-center text-lg-start">
                    IP ADDRESS
                  </small>
                  <h2 className="text-center text-lg-start">{ip}</h2>
                </div>
                <div className="vr my-3 d-none d-lg-block"></div>
                <div className="d-flex flex-column gap-lg-3 gap-1 infoBlock">
                  <small className="text-center text-lg-start">LOCATION</small>
                  <h2 className="text-center text-lg-start">
                    {country}, {region}
                  </h2>
                </div>
                <div className="vr my-3 d-none d-lg-block"></div>
                <div className="d-flex flex-column gap-lg-3 gap-1 infoBlock">
                  <small className="text-center text-lg-start">TIMEZONE</small>
                  <h2 className="text-center text-lg-start">UTC{timezone}</h2>
                </div>
                <div className="vr my-3 d-none d-lg-block"></div>
                <div className="d-flex flex-column gap-lg-3 gap-1 infoBlock">
                  <small className="text-center text-lg-start">ISP</small>
                  <h2 className="text-center text-lg-start">{isp}</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
